### ISSUE TITLE
Logging in fails.

### ISSUE THREAD

**Issue by tetraoxygen** [kajchang/StudentVue#2]
Whenever I try to login, I get the following error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/studentvue/scraper.py", line 22, in __init__
    form['username'] = username
TypeError: 'NoneType' object does not support item assignment
>>> sv = StudentVue('XXXX', 'XXXX', 'XXXX')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/studentvue/scraper.py", line 22, in __init__
    form['username'] = username
TypeError: 'NoneType' object does not support item assignment
```

**Comment by LoganMD** [comment]
I am experiencing this issue too, i'm not entirely sure why it isn't working

**Comment by kaijchang** [comment]
Sorry, just saw this, looking into it.

**Comment by LoganMD** [comment]
Thank you! School is starting soon, so fixing this would be a life saver

**Comment by kaijchang** [comment]
@LoganMD It's working for me, @tetraoxygen 's issue seems to be that it can't locate the login form, probably because the provided portal url is wrong or it's formatted differently. For your portal, does the login page url look like this: `https://XXX.XXX.XXX/PXP2_Login_Student.aspx?regenerateSessionId=True`?

**Comment by LoganMD** [comment]
Yes, it looks exactly like that

**Comment by kaijchang** [comment]
What are you providing for the domain name argument? It should just be the base, for me it's: `portal.sfusd.edu`.

**Comment by LoganMD** [comment]
The url studentvue is hosted on is ca-egusd-psv.edupoint.com

**Comment by kaijchang** [comment]
Can you post the stack trace you get? @tetraoxygen 's is out-dated.
It's able to find the form for me, but I obviously can't log in.
```python
>>> sv = StudentVue('test', 'test', 'ca-egusd-psv.edupoint.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kai/programming/StudentVue/studentvue/studentvue.py", line 40, in __init__
    raise ValueError('Incorrect Username or Password')
ValueError: Incorrect Username or Password
```

**Comment by tetraoxygen** [comment]
My district is https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx for the login page.

**Comment by tetraoxygen** [comment]
So I think the /ocsd/ is throwing it for a loop.

**Comment by kaijchang** [comment]
Yeah, try with `oc.cesdk12.org/ocsd`.
If that works, I can clarify it in the README.

**Comment by tetraoxygen** [comment]
Doing that now

**Comment by LoganMD** [comment]
Strange, It's not throwing any errors anymore...

**Comment by kaijchang** [comment]
Maybe it was an old version?

**Comment by LoganMD** [comment]
I think so

**Comment by LoganMD** [comment]
I'm glad it works now though, i can get to work on my google assistant gradebook now!

**Comment by LoganMD** [comment]
However, i *am* getting an error with `sv.getSchoolInfo()`

`Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print(sv.getSchoolInfo())
  File "C:\Users\ldoos\Desktop\studentvue\StudentVue\studentvue\studentvue.py", line 127, in getSchoolInfo
    for td in tds
  File "C:\Users\ldoos\Desktop\studentvue\StudentVue\studentvue\studentvue.py", line 127, in <listcomp>
    for td in tds
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by kaijchang** [comment]
I was still working on pulling grades with the new StudentVue layout before I stopped working on this, but I can look into it again for you.

**Comment by LoganMD** [comment]
Up to you. It's your repo after all...

**Comment by kaijchang** [comment]
It's something that was on my list anyways, so it's no problem.

**Comment by kaijchang** [comment]
What does the url look like? I have it like this: `https://{}/PXP2_SchoolInformation.aspx?AGU=0`.

**Comment by LoganMD** [comment]
`https://{}/PXP2_SchoolInformation.aspx?AGU=0`

**Comment by LoganMD** [comment]
I could send you the raw aspx file if it helps

**Comment by kaijchang** [comment]
That would help a lot, thanks. A lot of this is just modeled after my school's info because that's all I had to work with.

**Comment by LoganMD** [comment]
Where can i send it? I'm afraid it might have my login details, so i don't want to send it publically. Do you have a twitter or discord? Google drive?

**Comment by kaijchang** [comment]
kachang#2951 on Discord. Thanks!
Edit: Fixed in 4e1b4cd002cd4eb523cf8df9cecd2e126938c4a2.

**Comment by kaijchang** [comment]
Did it work, @tetraoxygen ?

**Comment by tetraoxygen** [comment]
Sorry, something came up and I went on a short trip with my family. Will report back ASAP.

**Comment by kaijchang** [comment]
A lot of work on this library is blocked until the school year and portal start up again.

**Comment by tetraoxygen** [comment]
I'm still getting this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/studentvue/studentvue.py", line 40, in __init__
    raise ValueError('Incorrect Username or Password')
ValueError: Incorrect Username or Password`

I'll be doing a beta of my app which employs this library this fall. I'd love to help with development on this whenever possible.

**Comment by tetraoxygen** [comment]
This was using the revised URL and the latest version of the library.

**Comment by kaijchang** [comment]
@tetraoxygen , it seems to be locating the login form correctly, which is good. On first glance, I can't see anything different on your login page.

The relevant login code is here:

https://github.com/kajchang/StudentVue/blob/27dc3f76e97f4c025cab17a6426a0cef1c0a3f75/studentvue/studentvue.py#L25-L40


It seems to be able to find and fill in the correct form fields, but it doesn't redirect to the same landing url. StudentVue redirects the POST request, either back onto the login page or into your account, and the library uses the redirect url to check if you're logged in.

If the credentials are correct, then most likely the issue is that you don't get redirected to `https://oc.cesdk12.org/ocsd/Home_PXP2.aspx` when you log in, so it thinks that you're unsuccessful even when you actually logged in, but just got redirected to a different page.

**Comment by tetraoxygen** [comment]
Appears to redirect to `https://oc.cesdk12.org/ocsd/Home_PXP2.aspx`. With that said, it does go through multiple hoops to get there iirc.

I have a video of me logging in normally if that would help.

**Comment by tetraoxygen** [comment]
My district also refuses to actually log in without a `VIEWSTATE` from my simple cURL tests, which might be impacting this here.

**Comment by kaijchang** [comment]
I ran into that too, but this part of the code copies over all the hidden inputs into the `form_data`:
https://github.com/kajchang/StudentVue/blob/27dc3f76e97f4c025cab17a6426a0cef1c0a3f75/studentvue/studentvue.py#L30-L31

**Comment by kaijchang** [comment]
Did you get it to work with cURL?

**Comment by tetraoxygen** [comment]
Yep, I figured that the only things you _needed_ were `VIEWSTATE`, `username`, and `password`. I had the command saved somewhere, gimme a sec

**Comment by kaijchang** [comment]
`__VIEWSTATE` or `VIEWSTATE`?

**Comment by tetraoxygen** [comment]
Sorry, `__VIEWSTATE`.

**Comment by tetraoxygen** [comment]
Something like this is what the browser outputs for me:
`curl 'https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Origin: https://oc.cesdk12.org' -H 'Upgrade-Insecure-Requests: 1' -H 'DNT: 1' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Referer: https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?Logout=1&regenerateSessionId=True' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: cookie_synergy_psv_cesdk12=2903764166.20480.0000; PVUE=1; ASP.NET_SessionId=xird1pvkh44pudjufse3fqgb' --data '__VIEWSTATE=oUJA2wE9XF0dVIsIHBdJml25HJLtt92UgMUiesV2OMV%2FB4dQaQ3oukIlGOyPMJ5d8honDl1TTwiCtTqPCeFBXpu0feWDGgY%2FjztyZefWeEM%3D&__VIEWSTATEGENERATOR=019B6102&__EVENTVALIDATION=TtXupHYmPVckfcTen00GY85h1VZNrEAkv%2FK0uV2gCpvjZaQXB8LkEv%2Bjp4V3BvYpGzDswp5o094QOKFFTqTqYEOcO89y9E4F%2BjR%2BiHSQnwxWf54KItROPnx0ny%2F9un%2Fi8sZiy%2Brw9VTRnNDl8SthiTlM6qvdQjG15YuVRJqcm98%3D&ctl00%24MainContent%24username=charles.b.welsh&ctl00%24MainContent%24password=******' --compressed`

I have a trimmed version _somewhere_, but I'm having a hard time finding it.

**Comment by tetraoxygen** [comment]
At least in my experience, I was able to trim out `__VIEWSTATEGENERATOR` with little issue. Getting rid of `__EVENTVALIDATION` just started breaking things for me.

**Comment by tetraoxygen** [comment]
So what it seems like the request needs to include is:
- `__VIEWSTATE`
- `__EVENTVALIDATION`
and obviously,
- `username`
- `password`.

Sorry if I'm repeating what's already been figured out.

**Comment by tetraoxygen** [comment]
`curl 'https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Origin: https://oc.cesdk12.org' -H 'Upgrade-Insecure-Requests: 1' -H 'DNT: 1' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Referer: https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: cookie_synergy_psv_cesdk12=2903764166.20480.0000; PVUE=1; ASP.NET_SessionId=5lmfqr4ighfjhxiajghzauw5' --data '__VIEWSTATE=8wQEbmShcOlRpK0n1d40RlyzuSqi1RuFkDpVTvd92O8BxWdN9g%2B5rqmWdR4Xg%2F1zPQepPZSths4i1B2ZvY29wkseeIcv3wfXktfcptEg30g%3D&__EVENTVALIDATION=aGbhZW9sGmnVBgoS0radN1SWOpOnKJT8%2FhEQOIbIoyJhlqo96dMNjZqx%2F9YNaSNEsP%2FBH7VCBzw2w2CRRWBk4fyQN8EaPHXNtr3MSvWjusuUDKrPsk%2F3ixRF66nW4lc8kI5158KeJbTswtidW8jJj6QJy3skQuVS%2FwNQS5b%2Bb90%3D&ctl00%24MainContent%24username=charles.b.welsh&ctl00%24MainContent%24password=******' --compressed
` works, but trimming out `__VIEWSTATE` produces this: 
```<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, user-scalable=yes" /><title>
	StudentVUE
</title><meta content="en-US" name="language" /><meta content="private - general audiences" name="rating" /><meta content="2005 - Edupoint,Inc" name="copyright" /><meta content="Edupoint, LLC" name="author" /><link rel="Shortcut Icon" href="synergy.ico" />

    <script type="text/javascript" src="resources/GBResources/gbapp_pvue.js"></script>

    <script type="text/javascript">
        var OEN = { Configurations: {} };
        window.PXP = window.PXP || { Translations: {} };
        window.ST = window.ST || {};
        window.ST.Translations = window.ST.Translations || {};

        PXP.UseGoogleAPI = false;
	PXP.Translations.ReportTryAgain = 'The document is being built.  Please try again in a few moments.';
	PXP.AccessibilityMode = false;
	PXP.UsePXP2Interface = true;
	OAUTH_SERVICE_REPOSITORY = 'https://oc.cesdk12.org//oauth_svc/';

    </script>


<script id="ctl00_Loader" type="text/javascript">window.LoadRemoteScript = function (resourceClientID, url) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
var Script = document.createElement('script');
Script.src = url;
Script.async = false;
Script.id = resourceClientID;
document.head.appendChild(Script);
};
};
window.LoadLocalStyleSheet = function (resourceClientID, text) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
var Script = document.createElement('script');
Script.type='text/css';
Script.id = resourceClientID;
Script.innerHTML = text;
document.head.appendChild(Script);
};
};
window.LoadRemoteStyleSheet = function (resourceClientID, url) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
if (document.createStyleSheet) {
document.createStyleSheet(url);
} else {
$('<link>')
.appendTo('head')
.attr({type : 'text/css', rel : 'stylesheet'})
.attr({id : resourceClientID})
.attr('href', url);
}
};
};
</script><link id="ctl00_Schemes_font-awesome_min_css" href="/OCSD/Schemes/font-awesome.min.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><link id="ctl00_Schemes_PXP2_PXP2_Global_css" href="/OCSD/Schemes/PXP2/PXP2_Global.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><link id="ctl00_Schemes_PXP_Form_css" href="/OCSD/Schemes/PXP_Form.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_js_ST_es6-promise_auto_min_js" src="/OCSD/js/ST/es6-promise.auto.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_json2_min_js" src="/OCSD/js/PXP/json2.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_GBResources_jquery_3_1_1_min_js" src="/OCSD/resources/GBResources/jquery_3_1_1_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><link id="ctl00_GBResources_jquery_ui_min_css" href="/OCSD/resources/GBResources/jquery_ui_min.css?2019-07-30T12%3a38%3a06.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_GBResources_jquery_ui_min_js" src="/OCSD/resources/GBResources/jquery_ui_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_PXP_jquery_ui_touch-punch_min_js" src="/OCSD/js/PXP/PXP_jquery.ui.touch-punch.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_PXPUtility_js" src="/OCSD/js/PXP/PXPUtility.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><link id="ctl00_GBResources_bootstrap_3_min_css" href="/OCSD/resources/GBResources/bootstrap_3_min.css?2019-07-30T12%3a38%3a06.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_GBResources_bootstrap_3_min_js" src="/OCSD/resources/GBResources/bootstrap_3_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><link id="ctl00_Schemes_PXP2_PXP2_login_css" href="/OCSD/Schemes/PXP2/PXP2_login.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_js_PXP_PXP2_Login_js" src="/OCSD/js/PXP/PXP2_Login.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><link id="ctl00_Schemes_PXP2_PXP2_LanguageBar_css" href="/OCSD/Schemes/PXP2/PXP2_LanguageBar.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link></head>
<body id="ctl00_MainBody" class="browser-Chrome bver-75_0">
    <div aria-label="Accessiblity Options" class="sr-only">
        <a href="accessibility.html" target="_blank">Synergy Accessibility Tips</a>
        <a href="#" role="button" id="AccessButton" data-action="ToggleAccessibleMode">Accessibility Mode</a>
    </div>

    <div class="container">
        <div id="ctl00_USER_ERROR"></div>


    <h1 id="LoginSVUE">StudentVUE Account Access</h1>

    <div class="row equal">
        <div class="login-content" style="margin: auto">


            <div class="panel panel-default" style="width:100%">
                <h2 id="ctl00_MainContent_LoginMessage" class="panel-heading">Login</h2>
                <div class="panel-body">
                    <span id="DistrictName">Oregon City School District 062</span>

                    <form name="aspnetForm" method="post" action="./PXP2_Login_Student.aspx?regenerateSessionId=True" id="aspnetForm">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="tWuBLxpdbBe/QPg7+XWV3Gwr2OHDZcdGr7h9ASBoq9cnBpRyizMcJVTOMTVCZ3Y8XysBr7HtUoDuhRrseOFVkJywBj5sWOWbCsxeX/amyqA=" />
</div>


<script type="text/javascript">
//<![CDATA[
window.LoadRemoteStyleSheet('Schemes_font-awesome_min_css', '/OCSD/Schemes/font-awesome.min.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_Global_css', '/OCSD/Schemes/PXP2/PXP2_Global.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP_Form_css', '/OCSD/Schemes/PXP_Form.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_ST_es6-promise_auto_min_js', '/OCSD/js/ST/es6-promise.auto.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_json2_min_js', '/OCSD/js/PXP/json2.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('GBResources_jquery_3_1_1_min_js', '/OCSD/resources/GBResources/jquery_3_1_1_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteStyleSheet('GBResources_jquery_ui_min_css', '/OCSD/resources/GBResources/jquery_ui_min.css?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('GBResources_jquery_ui_min_js', '/OCSD/resources/GBResources/jquery_ui_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('js_PXP_PXP_jquery_ui_touch-punch_min_js', '/OCSD/js/PXP/PXP_jquery.ui.touch-punch.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_PXPUtility_js', '/OCSD/js/PXP/PXPUtility.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('GBResources_bootstrap_3_min_css', '/OCSD/resources/GBResources/bootstrap_3_min.css?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('GBResources_bootstrap_3_min_js', '/OCSD/resources/GBResources/bootstrap_3_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_login_css', '/OCSD/Schemes/PXP2/PXP2_login.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_PXP2_Login_js', '/OCSD/js/PXP/PXP2_Login.js?2019-08-02T21%3a00%3a49.0000000');
var CURRENT_WEB_PORTAL='StudentVUE';var applicationRoot='/OCSD/';window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_LanguageBar_css', '/OCSD/Schemes/PXP2/PXP2_LanguageBar.css?2019-08-02T21%3a00%3a49.0000000');
//]]>
</script>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="019B6102" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="zIJXdXB4ChO5WQ5aIJ1qmVwienbq8h3Yg4Nxm2cd08SeRAy0xU3nGFlFXs5mJCsKZAXDcpLx9niU55F5nPxaJeq5YWqFqZG7wagCsJSSBUcYdjmLIf62U8uegO6qJ14y0wqAErUzRGmAA50n/F2IT8yz3vSZkLiFAAUYVEGN5YA=" />
</div>
                        <div class="form-group">
                            <label id="LoginUserName" for="ctl00_MainContent_username">User Name:</label>
                            <input name="ctl00$MainContent$username" type="text" id="ctl00_MainContent_username" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label id="LoginPassword" for="ctl00_MainContent_password">Password:</label>
				            <input name="ctl00$MainContent$password" type="password" id="ctl00_MainContent_password" class="form-control" />
                            <div class="pxp-forgot-password-link">

                            </div>
                        </div>
                        <div class="form-group center">
				            <input name="ctl00$MainContent$Submit1" type="submit" id="ctl00_MainContent_Submit1" value="Login" class="btn btn-primary" onclick="this.disabled = true; this.form.submit();" />
                        </div>
                    </form>
                </div>

                <div class="login-more">
                    <div class="expander">
                        <span class="btn-more" data-action="ToggleMoreOptions">
                            More Options
                            <i class="glyphicon"></i>
                        </span>
                    </div>
                    <div class="more-options">
                        <p id="ctl00_MainContent_ActMsgNoLink" align="center"><span class="largeText">
                            Contact your school if you do not have your account details.
                        </span></p>

                        <ul>

                            <li></li>


                            <li class="separator" role="separator"></li>
                            <li><a class="pxp-login-more-link" href="https://itunes.apple.com/us/app/studentvue/id412050327?mt=8">
                                <i class="fa fa-apple" style="color:#0000ff"></i>
                                <span>iPhone App</span>
                            </a></li>
                            <li><a class="pxp-login-more-link" href="https://market.android.com/details?id=com.FreeLance.StudentVUE">
                                <i class="fa fa-android" style="color:#00ff00"></i>
                                <span>Android App</span>
                            </a></li>
                            <li><span class="pxp-login-more-link">
                                <i class="fa fa-link" style="color:#000088"></i>
                                <span>Mobile App URL</span>
                                <span style="font-size:12px">https://oc.cesdk12.org/</span>
                            </span></li>

                        </ul>
                    </div>
                </div>

                <div class="panel-footer" style="text-align:left; padding:5px">
                    <div id="ctl00_MainContent_ctl01_Languages" class="languages" role="region" aria-label="Languages">
    <ul class="languages">

                <li><a title="English" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=1" data-is-current="True">English </a></li>

                <li><a title="Spanish" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=45" data-is-current="False">Español </a></li>

                <li><a title="Russian" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=39" data-is-current="False">Russian </a></li>

    </ul>
</div>



                </div>
            </div>
        </div>
    </div>

    <div class="row center">
        <span id="ctl00_MainContent_ERROR"></span>
    </div>

    </div>

    <footer id="ctl00_PXPFooter" class="footer hide-for-print" aria-label="Footer">
        <div class="action-bar">
            <div role="region" aria-label="System links" id="SystemLinks">
                <ul class="system-links">

                        <li><a href="PXP2_Login.aspx?Logout=1" id="ctl00_lnkLogin">Return to common login</a></li>

                    <li><a href="PXP2_Contact.aspx" id="ctl00_lnkContact">Contact</a></li>
                    <li><a href="PXP2_Privacy.aspx" id="ctl00_lnkPrivacy">Privacy</a></li>
                </ul>
            </div>

            <div id="ctl00_ctl10_Languages" class="languages" role="region" aria-label="Languages">
    <ul class="languages">

                <li><a title="English" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=1" data-is-current="True">English </a></li>

                <li><a title="Spanish" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=45" data-is-current="False">Español </a></li>

                <li><a title="Russian" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=39" data-is-current="False">Russian </a></li>

    </ul>
</div>



        </div>

        <div id="legal" class="center">
            <a target="_blank" href="http://www.edupoint.com/">
                <img border="0" style="padding-bottom: 3px; border: 0px" alt="Edupoint Educational Systems" src="Images/ST_Revelation/EduPointLogo_WHITE.png"></a>
            <br />
            &copy;Copyright 2019 Edupoint, LLC
        </div>

        <div id="accessToggle">
            <i class="glyphicon glyphicon-ok checked"></i>
            <a href="#" role="button" data-action="ToggleAccessibleMode">Accessibility Mode</a>
        </div>
    </footer>


</body>
</html>
Charlies-MacBook-Pro:~ cwelsh$ curl 'https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Origin: https://oc.cesdk12.org' -H 'Upgrade-Insecure-Requests: 1' -H 'DNT: 1' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Referer: https://oc.cesdk12.org/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: cookie_synergy_psv_cesdk12=2903764166.20480.0000; PVUE=1; ASP.NET_SessionId=5lmfqr4ighfjhxiajghzauw5' --data '__EVENTVALIDATION=aGbhZW9sGmnVBgoS0radN1SWOpOnKJT8%2FhEQOIbIoyJhlqo96dMNjZqx%2F9YNaSNEsP%2FBH7VCBzw2w2CRRWBk4fyQN8EaPHXNtr3MSvWjusuUDKrPsk%2F3ixRF66nW4lc8kI5158KeJbTswtidW8jJj6QJy3skQuVS%2FwNQS5b%2Bb90%3D&ctl00%24MainContent%24username=charles.b.welsh&ctl00%24MainContent%24password=******' --compressed

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, user-scalable=yes" /><title>
	StudentVUE
</title><meta content="en-US" name="language" /><meta content="private - general audiences" name="rating" /><meta content="2005 - Edupoint,Inc" name="copyright" /><meta content="Edupoint, LLC" name="author" /><link rel="Shortcut Icon" href="synergy.ico" />

    <script type="text/javascript" src="resources/GBResources/gbapp_pvue.js"></script>

    <script type="text/javascript">
        var OEN = { Configurations: {} };
        window.PXP = window.PXP || { Translations: {} };
        window.ST = window.ST || {};
        window.ST.Translations = window.ST.Translations || {};

        PXP.UseGoogleAPI = false;
	PXP.Translations.ReportTryAgain = 'The document is being built.  Please try again in a few moments.';
	PXP.AccessibilityMode = false;
	PXP.UsePXP2Interface = true;
	OAUTH_SERVICE_REPOSITORY = 'https://oc.cesdk12.org//oauth_svc/';

    </script>


<script id="ctl00_Loader" type="text/javascript">window.LoadRemoteScript = function (resourceClientID, url) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
var Script = document.createElement('script');
Script.src = url;
Script.async = false;
Script.id = resourceClientID;
document.head.appendChild(Script);
};
};
window.LoadLocalStyleSheet = function (resourceClientID, text) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
var Script = document.createElement('script');
Script.type='text/css';
Script.id = resourceClientID;
Script.innerHTML = text;
document.head.appendChild(Script);
};
};
window.LoadRemoteStyleSheet = function (resourceClientID, url) {
var resourceSelector = '[id*=' + resourceClientID + ']';
if ($(resourceSelector).length == 0) {
if (document.createStyleSheet) {
document.createStyleSheet(url);
} else {
$('<link>')
.appendTo('head')
.attr({type : 'text/css', rel : 'stylesheet'})
.attr({id : resourceClientID})
.attr('href', url);
}
};
};
</script><link id="ctl00_Schemes_font-awesome_min_css" href="/OCSD/Schemes/font-awesome.min.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><link id="ctl00_Schemes_PXP2_PXP2_Global_css" href="/OCSD/Schemes/PXP2/PXP2_Global.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><link id="ctl00_Schemes_PXP_Form_css" href="/OCSD/Schemes/PXP_Form.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_js_ST_es6-promise_auto_min_js" src="/OCSD/js/ST/es6-promise.auto.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_json2_min_js" src="/OCSD/js/PXP/json2.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_GBResources_jquery_3_1_1_min_js" src="/OCSD/resources/GBResources/jquery_3_1_1_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><link id="ctl00_GBResources_jquery_ui_min_css" href="/OCSD/resources/GBResources/jquery_ui_min.css?2019-07-30T12%3a38%3a06.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_GBResources_jquery_ui_min_js" src="/OCSD/resources/GBResources/jquery_ui_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_PXP_jquery_ui_touch-punch_min_js" src="/OCSD/js/PXP/PXP_jquery.ui.touch-punch.min.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><script id="ctl00_js_PXP_PXPUtility_js" src="/OCSD/js/PXP/PXPUtility.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><link id="ctl00_GBResources_bootstrap_3_min_css" href="/OCSD/resources/GBResources/bootstrap_3_min.css?2019-07-30T12%3a38%3a06.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_GBResources_bootstrap_3_min_js" src="/OCSD/resources/GBResources/bootstrap_3_min.js?2019-07-30T12%3a38%3a06.0000000" type="text/javascript"></script><link id="ctl00_Schemes_PXP2_PXP2_login_css" href="/OCSD/Schemes/PXP2/PXP2_login.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link><script id="ctl00_js_PXP_PXP2_Login_js" src="/OCSD/js/PXP/PXP2_Login.js?2019-08-02T21%3a00%3a49.0000000" type="text/javascript"></script><link id="ctl00_Schemes_PXP2_PXP2_LanguageBar_css" href="/OCSD/Schemes/PXP2/PXP2_LanguageBar.css?2019-08-02T21%3a00%3a49.0000000" type="text/css" rel="stylesheet"></link></head>
<body id="ctl00_MainBody" class="browser-Chrome bver-75_0">
    <div aria-label="Accessiblity Options" class="sr-only">
        <a href="accessibility.html" target="_blank">Synergy Accessibility Tips</a>
        <a href="#" role="button" id="AccessButton" data-action="ToggleAccessibleMode">Accessibility Mode</a>
    </div>

    <div class="container">
        <div id="ctl00_USER_ERROR"></div>


    <h1 id="LoginSVUE">StudentVUE Account Access</h1>

    <div class="row equal">
        <div class="login-content" style="margin: auto">


            <div class="panel panel-default" style="width:100%">
                <h2 id="ctl00_MainContent_LoginMessage" class="panel-heading">Login</h2>
                <div class="panel-body">
                    <span id="DistrictName">Oregon City School District 062</span>

                    <form name="aspnetForm" method="post" action="./PXP2_Login_Student.aspx?regenerateSessionId=True" id="aspnetForm">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="UUF5JAq4HeYa1orlrdjr07nTMdINVJbxmfwwYL0PMn2WtZrWRYuEwdvT3qKCaMuZdkWf6dzziDWkQryHNark0uix0iNJhK1TDZOG7oehBFM=" />
</div>


<script type="text/javascript">
//<![CDATA[
window.LoadRemoteStyleSheet('Schemes_font-awesome_min_css', '/OCSD/Schemes/font-awesome.min.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_Global_css', '/OCSD/Schemes/PXP2/PXP2_Global.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP_Form_css', '/OCSD/Schemes/PXP_Form.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_ST_es6-promise_auto_min_js', '/OCSD/js/ST/es6-promise.auto.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_json2_min_js', '/OCSD/js/PXP/json2.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('GBResources_jquery_3_1_1_min_js', '/OCSD/resources/GBResources/jquery_3_1_1_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteStyleSheet('GBResources_jquery_ui_min_css', '/OCSD/resources/GBResources/jquery_ui_min.css?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('GBResources_jquery_ui_min_js', '/OCSD/resources/GBResources/jquery_ui_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('js_PXP_PXP_jquery_ui_touch-punch_min_js', '/OCSD/js/PXP/PXP_jquery.ui.touch-punch.min.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_PXPUtility_js', '/OCSD/js/PXP/PXPUtility.js?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteStyleSheet('GBResources_bootstrap_3_min_css', '/OCSD/resources/GBResources/bootstrap_3_min.css?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteScript('GBResources_bootstrap_3_min_js', '/OCSD/resources/GBResources/bootstrap_3_min.js?2019-07-30T12%3a38%3a06.0000000');
window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_login_css', '/OCSD/Schemes/PXP2/PXP2_login.css?2019-08-02T21%3a00%3a49.0000000');
window.LoadRemoteScript('js_PXP_PXP2_Login_js', '/OCSD/js/PXP/PXP2_Login.js?2019-08-02T21%3a00%3a49.0000000');
var CURRENT_WEB_PORTAL='StudentVUE';var applicationRoot='/OCSD/';window.LoadRemoteStyleSheet('Schemes_PXP2_PXP2_LanguageBar_css', '/OCSD/Schemes/PXP2/PXP2_LanguageBar.css?2019-08-02T21%3a00%3a49.0000000');
//]]>
</script>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="019B6102" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="cMSaKf5lQC4yuLFRyLslRzanGC/f5ARnM6ohUC2SyDSDNDP1XN0dY0yZCt2/8vp34n7OKO1hTjfaY3T+khFtLO1h80S0F68fkx8JucvBZTnaMiQH00BILpd4nNsgTKEH0PcWxCwbG+m34VhQFNSz/C5in4tjBvWGTWdikjZg4dM=" />
</div>
                        <div class="form-group">
                            <label id="LoginUserName" for="ctl00_MainContent_username">User Name:</label>
                            <input name="ctl00$MainContent$username" type="text" id="ctl00_MainContent_username" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label id="LoginPassword" for="ctl00_MainContent_password">Password:</label>
				            <input name="ctl00$MainContent$password" type="password" id="ctl00_MainContent_password" class="form-control" />
                            <div class="pxp-forgot-password-link">

                            </div>
                        </div>
                        <div class="form-group center">
				            <input name="ctl00$MainContent$Submit1" type="submit" id="ctl00_MainContent_Submit1" value="Login" class="btn btn-primary" onclick="this.disabled = true; this.form.submit();" />
                        </div>
                    </form>
                </div>

                <div class="login-more">
                    <div class="expander">
                        <span class="btn-more" data-action="ToggleMoreOptions">
                            More Options
                            <i class="glyphicon"></i>
                        </span>
                    </div>
                    <div class="more-options">
                        <p id="ctl00_MainContent_ActMsgNoLink" align="center"><span class="largeText">
                            Contact your school if you do not have your account details.
                        </span></p>

                        <ul>

                            <li></li>


                            <li class="separator" role="separator"></li>
                            <li><a class="pxp-login-more-link" href="https://itunes.apple.com/us/app/studentvue/id412050327?mt=8">
                                <i class="fa fa-apple" style="color:#0000ff"></i>
                                <span>iPhone App</span>
                            </a></li>
                            <li><a class="pxp-login-more-link" href="https://market.android.com/details?id=com.FreeLance.StudentVUE">
                                <i class="fa fa-android" style="color:#00ff00"></i>
                                <span>Android App</span>
                            </a></li>
                            <li><span class="pxp-login-more-link">
                                <i class="fa fa-link" style="color:#000088"></i>
                                <span>Mobile App URL</span>
                                <span style="font-size:12px">https://oc.cesdk12.org/</span>
                            </span></li>

                        </ul>
                    </div>
                </div>

                <div class="panel-footer" style="text-align:left; padding:5px">
                    <div id="ctl00_MainContent_ctl01_Languages" class="languages" role="region" aria-label="Languages">
    <ul class="languages">

                <li><a title="English" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=1" data-is-current="True">English </a></li>

                <li><a title="Spanish" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=45" data-is-current="False">Español </a></li>

                <li><a title="Russian" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=39" data-is-current="False">Russian </a></li>

    </ul>
</div>



                </div>
            </div>
        </div>
    </div>

    <div class="row center">
        <span id="ctl00_MainContent_ERROR"></span>
    </div>

    </div>

    <footer id="ctl00_PXPFooter" class="footer hide-for-print" aria-label="Footer">
        <div class="action-bar">
            <div role="region" aria-label="System links" id="SystemLinks">
                <ul class="system-links">

                        <li><a href="PXP2_Login.aspx?Logout=1" id="ctl00_lnkLogin">Return to common login</a></li>

                    <li><a href="PXP2_Contact.aspx" id="ctl00_lnkContact">Contact</a></li>
                    <li><a href="PXP2_Privacy.aspx" id="ctl00_lnkPrivacy">Privacy</a></li>
                </ul>
            </div>

            <div id="ctl00_ctl10_Languages" class="languages" role="region" aria-label="Languages">
    <ul class="languages">

                <li><a title="English" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=1" data-is-current="True">English </a></li>

                <li><a title="Spanish" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=45" data-is-current="False">Español </a></li>

                <li><a title="Russian" href="/ocsd/PXP2_Login_Student.aspx?regenerateSessionId=True&LNG=39" data-is-current="False">Russian </a></li>

    </ul>
</div>



        </div>

        <div id="legal" class="center">
            <a target="_blank" href="http://www.edupoint.com/">
                <img border="0" style="padding-bottom: 3px; border: 0px" alt="Edupoint Educational Systems" src="Images/ST_Revelation/EduPointLogo_WHITE.png"></a>
            <br />
            &copy;Copyright 2019 Edupoint, LLC
        </div>

        <div id="accessToggle">
            <i class="glyphicon glyphicon-ok checked"></i>
            <a href="#" role="button" data-action="ToggleAccessibleMode">Accessibility Mode</a>
        </div>
    </footer>


</body>
</html>``` 

and removing `__EVENTVALIDATION` produces this: ```<!DOCTYPE html>
<html>
    <head>
        <title>Invalid postback or callback argument. &nbsp;Event validation is enabled using &lt;pages enableEventValidation=&quot;true&quot;/&gt; in configuration or &lt;%@ Page EnableEventValidation=&quot;true&quot; %&gt; in a page. &nbsp;For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them. &nbsp;If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/OCSD' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Invalid postback or callback argument. &nbsp;Event validation is enabled using &lt;pages enableEventValidation=&quot;true&quot;/&gt; in configuration or &lt;%@ Page EnableEventValidation=&quot;true&quot; %&gt; in a page. &nbsp;For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them. &nbsp;If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.ArgumentException: Invalid postback or callback argument. &nbsp;Event validation is enabled using &lt;pages enableEventValidation=&quot;true&quot;/&gt; in configuration or &lt;%@ Page EnableEventValidation=&quot;true&quot; %&gt; in a page. &nbsp;For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them. &nbsp;If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[ArgumentException: Invalid postback or callback argument.  Event validation is enabled using &lt;pages enableEventValidation=&quot;true&quot;/&gt; in configuration or &lt;%@ Page EnableEventValidation=&quot;true&quot; %&gt; in a page.  For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them.  If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.]
   System.Web.UI.ClientScriptManager.ValidateEvent(String uniqueId, String argument) +11821070
   System.Web.UI.Control.ValidateEvent(String uniqueID, String eventArgument) +143
   System.Web.UI.HtmlControls.HtmlInputText.LoadPostData(String postDataKey, NameValueCollection postCollection) +99
   System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad) +558
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2927
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3429.0

            </font>

    </body>
</html>
<!--
[ArgumentException]: Invalid postback or callback argument.  Event validation is enabled using &lt;pages enableEventValidation=&quot;true&quot;/&gt; in configuration or &lt;%@ Page EnableEventValidation=&quot;true&quot; %&gt; in a page.  For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them.  If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.
   at System.Web.UI.ClientScriptManager.ValidateEvent(String uniqueId, String argument)
   at System.Web.UI.Control.ValidateEvent(String uniqueID, String eventArgument)
   at System.Web.UI.HtmlControls.HtmlInputText.LoadPostData(String postDataKey, NameValueCollection postCollection)
   at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
[HttpUnhandledException]: Exception of type &#39;System.Web.HttpUnhandledException&#39; was thrown.
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
--><!--
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->```

**Comment by kaijchang** [comment]
I'm not really sure what's going on, because the request the library sends should be pretty much identical. If it's not too much trouble, can you try cloning the project and setting some breakpoints to check the `form_data` and `resp` variables:
https://github.com/kajchang/StudentVue/blob/27dc3f76e97f4c025cab17a6426a0cef1c0a3f75/studentvue/studentvue.py#L13-L37
Also, another problem I found was that trail slashes in the district domain weren't removed, but that shouldn't be relevant here.

**Comment by tetraoxygen** [comment]
I'm getting a `ModuleNotFound` error about the Models file, and I've run setup.py.

Here's the error log: 
```
Traceback (most recent call last):
  File "/Users/cwelsh/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Users/cwelsh/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/cwelsh/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/cwelsh/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/cwelsh/Desktop/StudentVue/studentvue/studentvue.py", line 9, in <module>
    import studentvue.models as models
  File "/Users/cwelsh/Desktop/StudentVue/studentvue/studentvue.py", line 9, in <module>
    import studentvue.models as models
ModuleNotFoundError: No module named 'studentvue.models'; 'studentvue' is not a package
```

**Comment by tetraoxygen** [comment]
Nevermind I'm dumb. I just imported the file directly.

**Comment by tetraoxygen** [comment]
`form_data` = ```<class 'dict'>: {'__VIEWSTATE': '2+3+oNK9IzGXkkiwFE2G343NmNPY/4yTrMUE912Wj3T4ZZtSo4rWiRPxiwIoaKdBVP3/aOBAdWjnS+BAlC4xkqVtuZEhgz7BdR09XCzPBk0=', '__VIEWSTATEGENERATOR': '019B6102', '__EVENTVALIDATION': '+l74qjtVcx7DjaSwDGUggzdzqVInRvEAbYT4Xp5yB48BSo05cPtq1tqzgMsr+vvnWeP1jhwAW5FfSCj4Kc3AQlyvsf2TJc47vDc8F2TkjxLLWWge25VLUb4IousWj1KPOabTbLvyVCAZOJQBPCN+B1176+abwsB/TalRAwYYuAo=', 'ctl00$MainContent$username': 'charles.b.welsh', 'ctl00$MainContent$password': '{REDACTED}', 'ctl00$MainContent$Submit1': 'Login'}```

**Comment by tetraoxygen** [comment]
`resp` = ```<Response [200]>```

**Comment by tetraoxygen** [comment]
Whereas in the browser, I've been getting 302 responses after POSTing

**Comment by tetraoxygen** [comment]
<img width="1543" alt="Screen Shot 2019-08-06 at 12 41 00" src="https://user-images.githubusercontent.com/20668045/62571938-75cbf380-b847-11e9-895d-adacd8c14365.png">

**Comment by tetraoxygen** [comment]
I don't see anything that should be obviously wrong. Perhaps the 200 response is to the wrong page and it's doing a `<meta>` redirect?

**Comment by tetraoxygen** [comment]
`resp` = ```_content = {bytes} b'\r\n<!DOCTYPE html>\r\n\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en">\r\n<head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=dev
_content_consumed = {bool} True
_next = {NoneType} None
apparent_encoding = {str} 'ISO-8859-1'
connection = {HTTPAdapter} <requests.adapters.HTTPAdapter object at 0x10d16fe90>
content = {bytes} b'\r\n<!DOCTYPE html>\r\n\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en">\r\n<head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=dev
cookies = {RequestsCookieJar} <RequestsCookieJar[<Cookie PVUE=1 for oc.cesdk12.org/>, <Cookie cookie_synergy_psv_cesdk12=2870209734.20480.0000 for oc.cesdk12.org/>]>
elapsed = {timedelta} 0:00:00.138049
encoding = {str} 'utf-8'
headers = {CaseInsensitiveDict} {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'text/html; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'X-AspNet-Version': '4.0.30319', 'Set-Cookie': 'PVUE=1; expires=Fri, 16-Aug-2019 19:49:25 GMT; path=/, cookie_synergy_psv_cesdk12=2870209734.20480.0000; expires=Wed, 07-Aug-2019 04:49:25 GMT; path=/; Httponly; Secure', 'X-Powered-By': 'ASP.NET', 'X-PSV': '1', 'Member': 'PSV1', 'Date': 'Tue, 06 Aug 2019 19:49:25 GMT', 'Content-Length': '12969', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Connection': 'Keep-Alive'}
history = {list} <class 'list'>: [<Response [302]>]
is_permanent_redirect = {bool} False
is_redirect = {bool} False
links = {dict} <class 'dict'>: {}
next = {NoneType} None
ok = {bool} True
raw = {HTTPResponse} <urllib3.response.HTTPResponse object at 0x10d2e2190>
reason = {str} 'OK'
request = {PreparedRequest} <PreparedRequest [GET]>
status_code = {int} 200
text = {str} '\r\n<!DOCTYPE html>\r\n\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en">\r\n<head><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width
url = {str} 'https://oc.cesdk12.org/ocsd/Home_PXP2.aspx'```

**Comment by kaijchang** [comment]
It looks like the login is successful. Look at the last bit `url = {str} 'https://oc.cesdk12.org/ocsd/Home_PXP2.aspx'`

I think it's just a problem with how the library checks if you succeeded or not. Do you have a trailing slash in the provided `districtdomain`? Can you verify that `'https://{}/Home_PXP2.aspx'.format(self.districtdomain)` is `'https://oc.cesdk12.org/ocsd/Home_PXP2.aspx'`?

**Comment by tetraoxygen** [comment]
Nope:
`districtdomain = 'https://oc.cesdk12.org/ocsd'`

**Comment by kaijchang** [comment]
What is `self.districtdomain`?

**Comment by tetraoxygen** [comment]
Same thing.

**Comment by kaijchang** [comment]
It still has the `https://` at the start?

**Comment by tetraoxygen** [comment]
Yes. It's literally the exact same string: `'https://oc.cesdk12.org/ocsd'` at least according to PyCharm.

**Comment by kaijchang** [comment]
That's confusing because you should get a requests error when you try to GET `'https://{}/PXP2_Login_Student.aspx?regenerateSessionId=True'` while formatting it with `'https://oc.cesdk12.org/ocsd'`.
And this part should remove the schema:
https://github.com/kajchang/StudentVue/blob/7540cceace4bf6ee4e9155672957f2782424a342/studentvue/studentvue.py#L20-L22

**Comment by tetraoxygen** [comment]
That's weird, I have this for those lines: 
```
self.districtdomain = urlparse(districtdomain).netloc if urlparse(
            districtdomain).netloc else urlparse(districtdomain).path
        self.session = requests.Session()
```

**Comment by tetraoxygen** [comment]
It appears to work when I swapped those out.

```
/usr/local/bin/python3.7 /Users/cwelsh/Desktop/StudentVue/studentvue/studentvue.py

Process finished with exit code 0
```

**Comment by tetraoxygen** [comment]
Let me try recloning.

**Comment by kaijchang** [comment]
You're able to log in now?

**Comment by tetraoxygen** [comment]
Yes and no.

**Comment by tetraoxygen** [comment]
It's not throwing an error, but I'm _only_ getting `Process finished with exit code 0`, and also the pip version is the old broken version.

**Comment by tetraoxygen** [comment]
```
from studentvue import StudentVue
sv = StudentVue("charles.b.welsh", "{REDACTED}", "https://oc.cesdk12.org/ocsd") # e.g. portal.sfusd.edu
print(sv.getStudentInfo())
``` 
is my test code

**Comment by kaijchang** [comment]
So, to confirm, nothing is happening? Are you sure that you're running the right file? `/usr/local/bin/python3.7 /Users/cwelsh/Desktop/StudentVue/studentvue/studentvue.py` looks like just the library file, unless you edited it.

**Comment by tetraoxygen** [comment]
My IDE was being weird. It works now, and getStudentInfo now returns `{}`.

**Comment by tetraoxygen** [comment]
If you get a moment, please update the pip package though.

**Comment by kaijchang** [comment]
So, to confirm, you can now login without an error, but getStudentInfo doesn't work?

**Comment by tetraoxygen** [comment]
Yep.

**Comment by kaijchang** [comment]
Do you know what the problem was?

**Comment by tetraoxygen** [comment]
No I don't. However, `getSchoolInfo` is working.

**Comment by tetraoxygen** [comment]
Apparently my school is only showing my emergency contacts, so it's not an issue with the library.

**Comment by tetraoxygen** [comment]
<img width="1440" alt="Screen Shot 2019-08-06 at 14 08 08" src="https://user-images.githubusercontent.com/20668045/62577438-d3663d00-b853-11e9-96df-cde28923b5a9.png">

**Comment by kaijchang** [comment]
Ok, if everything is working, I'll update the version and close this.
